// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUbwoNDiU0Xy_VmLAQxbQX-Xh8t0rcLo',
    appId: '1:363811228333:web:76cce51dc3826a192d9424',
    messagingSenderId: '363811228333',
    projectId: 'bosla-app',
    authDomain: 'bosla-app.firebaseapp.com',
    storageBucket: 'bosla-app.appspot.com',
    measurementId: 'G-6P5LHGDSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqLifvH2eK74CdASX2P5BE7nLCVc1KJg',
    appId: '1:363811228333:android:1d9a7ef0e0d7784d2d9424',
    messagingSenderId: '363811228333',
    projectId: 'bosla-app',
    storageBucket: 'bosla-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHr7R5HNGcZrMsUw6W03jj60NCIDhnJZI',
    appId: '1:363811228333:ios:4d2caa1f4849bca02d9424',
    messagingSenderId: '363811228333',
    projectId: 'bosla-app',
    storageBucket: 'bosla-app.appspot.com',
    iosClientId: '363811228333-ibklj5hab715jb5hq1840eob6uen82av.apps.googleusercontent.com',
    iosBundleId: 'com.example.bosala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHr7R5HNGcZrMsUw6W03jj60NCIDhnJZI',
    appId: '1:363811228333:ios:4d2caa1f4849bca02d9424',
    messagingSenderId: '363811228333',
    projectId: 'bosla-app',
    storageBucket: 'bosla-app.appspot.com',
    iosClientId: '363811228333-ibklj5hab715jb5hq1840eob6uen82av.apps.googleusercontent.com',
    iosBundleId: 'com.example.bosala',
  );
}
